const { 
  OnlineLoanModel, 
  PhysicalLoanModel, 
  InstallmentModel, 
  LoanTypeModel, 
  FixedDepositModel 
} = require("../models/loanModel");

/**
 * 1. ONLINE LOAN APPLICATION (FD-COLLATERALIZED)
 * This interacts with the 'apply_for_online_loan' stored procedure.
 */
exports.applyOnlineLoan = (req, res) => {
  const customerId = req.user?.customer_id;
  const { fdId, savingsId, loanTypeId, amount, duration } = req.body;

  // Level 1: Basic Input Validation
  if (!fdId || !savingsId || !loanTypeId || !amount || !duration) {
    return res.status(400).json({ 
      success: false, 
      message: "Required fields missing: fdId, savingsId, loanTypeId, amount, and duration must be provided." 
    });
  }

  if (amount <= 0 || duration <= 0) {
    return res.status(400).json({ 
      success: false, 
      message: "Amount and duration must be positive values." 
    });
  }

  const loanData = {
    customerId,
    fdId,
    savingsId,
    loanTypeId,
    amount: parseFloat(amount),
    duration: parseInt(duration)
  };

  // Level 2: Database Logic Execution
  OnlineLoanModel.apply(loanData, (err, result) => {
    if (err) {
      console.error("[OnlineLoan Error]:", err.message);
      
      // Handling Procedure-specific status codes
      if (err.message === 'INSUFFICIENT_COLLATERAL') {
        return res.status(403).json({ 
          success: false, 
          message: "Application rejected: Loan amount must not exceed 80% of the active Fixed Deposit value." 
        });
      }
      
      if (err.message === 'TRANSACTION_ERROR') {
        return res.status(500).json({ 
          success: false, 
          message: "Internal ledger failure. The transaction has been rolled back." 
        });
      }

      return res.status(500).json({ 
        success: false, 
        message: err.message || "An unexpected error occurred during loan disbursement." 
      });
    }
    
    // Level 3: Success response (Installments are automatically generated by DB trigger)
    res.status(201).json({
      success: true,
      message: "Loan approved and funds disbursed successfully.",
      data: result
    });
  });
};

/**
 * 2. PHYSICAL LOAN REQUEST (BRANCH-BASED)
 * For loans requiring manual review and employee approval.
 */
exports.requestPhysicalLoan = (req, res) => {
  const customerId = req.user?.customer_id;
  const { branchId, savingsId, loanTypeId, amount, duration, interestRate } = req.body;

  if (!branchId || !savingsId || !amount) {
    return res.status(400).json({ success: false, message: "Branch, Savings Account, and Amount are required." });
  }

  const loanData = {
    customerId,
    branchId,
    employeeId: null, // To be assigned by branch staff
    savingsId,
    loanTypeId,
    amount,
    duration,
    interestRate: interestRate || 15.0 // Default or type-based rate
  };

  PhysicalLoanModel.request(loanData, (err, result) => {
    if (err) {
      console.error("[PhysicalLoan Request Error]:", err);
      return res.status(500).json({ success: false, message: "Failed to submit loan application. Please try again later." });
    }
    res.status(201).json({ 
      success: true, 
      message: "Your application has been submitted to the branch. You will be notified once a credit officer reviews it.",
      applicationId: result.insertId 
    });
  });
};

/**
 * 3. LOAN REPAYMENT (INSTALLMENTS)
 * Interacts with 'pay_online_installment' stored procedure.
 */
exports.payLoanInstallment = (req, res) => {
  const { installmentId } = req.body;

  if (!installmentId) {
    return res.status(400).json({ success: false, message: "Installment ID is required for processing payment." });
  }

  InstallmentModel.payOnlineInstallment(installmentId, (err, result) => {
    if (err) {
      console.error("[Repayment Error]:", err.message);

      // Handle Stored Procedure specific errors
      if (err.message === 'INSUFFICIENT_FUNDS') {
        return res.status(402).json({ 
          success: false, 
          message: "Payment failed: Linked savings account has insufficient balance." 
        });
      }

      return res.status(400).json({ 
        success: false, 
        message: err.message || "Repayment processing failed." 
      });
    }

    res.status(200).json({ 
      success: true, 
      message: "Repayment successful. Account balance and loan schedule updated." 
    });
  });
};

/**
 * 4. LOAN DATA RETRIEVAL (DASHBOARD)
 */
exports.getCustomerLoans = (req, res) => {
  const customerId = req.user?.customer_id;

  OnlineLoanModel.getCustomerLoans(customerId, (err, loans) => {
    if (err) return res.status(500).json({ success: false, message: "Error fetching loan records." });
    res.status(200).json({ success: true, data: loans });
  });
};

exports.getLoanInstallments = (req, res) => {
  const { loanId } = req.params;
  const { type } = req.query; // 'online' or 'physical'

  if (!loanId || !type) {
    return res.status(400).json({ success: false, message: "Loan ID and Type (online/physical) are required." });
  }

  InstallmentModel.getPendingByLoan(loanId, type, (err, installments) => {
    if (err) return res.status(500).json({ success: false, message: "Error fetching payment schedule." });
    res.status(200).json({ success: true, data: installments });
  });
};

/**
 * 5. UTILITY DATA (FOR FORMS)
 */
exports.getEligibleCollateral = (req, res) => {
  const customerId = req.user?.customer_id;

  FixedDepositModel.getEligibleCollateral(customerId, (err, fds) => {
    if (err) return res.status(500).json({ success: false, message: "Error retrieving eligible FDs." });
    res.status(200).json({ success: true, data: fds });
  });
};

exports.getLoanTypes = (req, res) => {
  LoanTypeModel.getAll((err, types) => {
    if (err) return res.status(500).json({ success: false, message: "Error retrieving loan products." });
    res.status(200).json({ success: true, data: types });
  });
};